backend/articles/urls.py
from django.urls import path

from backend.articles.views import ArticlesList, ArticleDetail

app_name = 'articles'

urlpatterns = [
    path('<slug:slug>/', ArticleDetail.as_view(), name='detail'),
    path('', ArticlesList.as_view(), name='list')
]

backend/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path, re_path
from djangocms_helpers.sentry_500_error_handler.views import collect_500_error_user_feedback_view
from djangocms_helpers.sentry_500_error_handler.views import not_found_404_view

admin.site.enable_nav_sidebar = False

urlpatterns = [
        path('robots.txt', include('robots.urls')),
        # path('login-as-user/', include('hijack.urls', namespace='hijack')),
        path('taggit_autosuggest/', include('taggit_autosuggest.urls')),
        path('', include('link_all.api.urls')),
        path('filer/', include('filer.urls')),
        path('admin/', admin.site.urls),
        path('', include('aldryn_sso.urls')),
    ] + i18n_patterns(
        path('', include('aldryn_sso.urls_i18n')),
        path('articles/', include('backend.articles.urls', namespace='articles')),
        path('', include('cms.urls')),
    )

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

if not settings.DEBUG:
    handler500 = collect_500_error_user_feedback_view
    handler404 = not_found_404_view

backend/articles/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _ul
from djangocms_text_ckeditor.fields import HTMLField
from taggit.managers import TaggableManager

from backend.generic.db.models import TimestampedModel


class Article(TimestampedModel):
    slug = models.SlugField(unique=True, verbose_name=_ul('Slug'))
    image = models.ImageField(upload_to='articles/%Y/%m/%d')

    # Translatable fields.
    title_en = models.CharField(max_length=255, verbose_name=_ul('Name (EN)'))
    title_de = models.CharField(max_length=255, verbose_name=_ul('Name (DE)'))

    content_en = HTMLField(verbose_name=_ul('Content (EN)'))
    content_de = HTMLField(verbose_name=_ul('Content (DE)'))

    tags = TaggableManager()

    class Meta:
        verbose_name = _ul('article')
        verbose_name_plural = _ul('articles')
        ordering = ['-creation_date']

    def __str__(self):
        return self.title_en

backend/articles/forms.py
from django import forms
from taggit.models import Tag


class ArticleSearchForm(forms.Form):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        required=False,
    )

backend/articles/views.py
from django.views.generic import ListView, DetailView

from backend.articles.forms import ArticleSearchForm
from backend.articles.models import Article


class ArticleQuerysetMixin:
    queryset = Article.objects.all()


class ArticlesList(ArticleQuerysetMixin, ListView):
    template_name = 'articles/list.html'
    paginate_by = 8

    def get_queryset(self):
        queryset = super().get_queryset()
        search_form = ArticleSearchForm(data=self.request.GET)
        search_form.is_valid()
        if search_form.cleaned_data['tags']:
            queryset = queryset.filter(tags__in=search_form.cleaned_data['tags'])
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['search_form'] = ArticleSearchForm(initial=self.request.GET)
        return context


class ArticleDetail(ArticleQuerysetMixin, DetailView):
    template_name = 'articles/detail.html'

backend/articles/templates/articles/includes/article_card.html
{% load i18n easy_thumbnails_tags %}

{% get_current_language as LANGUAGE_CODE %}

<div class="card">
    {% thumbnail object.image 510x350 crop upscale as thumb %}
    {% if LANGUAGE_CODE == 'de' %}
        <img src="{{ thumb.url }}"
            class="card-img-top"
            alt="{{ object.title_de }}">
        <div class="card-body">
            <h5 class="card-title">
                <a href="{% url 'articles:detail' slug=object.slug %}">
                    {{ object.title_de }}
                </a>
            </h5>
            <p class="card-text">
                {{ object.content_de|truncatewords_html:15 }}
            </p>
            {% include 'articles/includes/view_more_btn.html' %}
        </div>
    {% else %}
        <img src="{{ thumb.url }}"
            class="card-img-top"
            alt="{{ object.title_en }}">
        <div class="card-body">
            <h5 class="card-title">
                <a href="{% url 'articles:detail' slug=object.slug %}">
                    {{ object.title_en }}
                </a>
            </h5>
            <p class="card-text">
                {{ object.content_en|truncatewords_html:15 }}
            </p>
            {% include 'articles/includes/view_more_btn.html' %}
        </div>
    {% endif %}
</div>

backend/articles/templates/articles/includes/article_detail.html
{% load i18n easy_thumbnails_tags %}

{% thumbnail object.image 510x350 crop upscale as thumb %}

<h2>{{ title }}</h2>

<h5>{% trans 'Created' %}: {{ object.creation_date|date }}</h5>

<div>
    <img src="{{ thumb.url }}">
</div>

<div>
    {{ content|safe }}
</div>

backend/articles/templates/articles/includes/view_more_btn.html
{% load i18n %}

<a href="{% url 'articles:detail' slug=object.slug %}" class="btn btn-primary btn-sm">{% translate 'View More' %}</a>